# Generated by Django 4.1.7 on 2023-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensordata",
            old_name="data",
            new_name="accel",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="disp",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
