# Generated by Django 4.1.7 on 2023-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphe", "0003_remove_sensordata_accel_remove_sensordata_disp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="gyro",
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
